services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: ${MC_VER}
      MEMORY: ${RAM}
      SEED: ${CUSTOM_SEED}
    ports:
      - "${MC_PORT}:${MC_PORT}"
    volumes:
      - /srv/minecraft:/data
    restart: unless-stopped